framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(FALLBACK_LOCALE)%'
        providers:
